### ISSUE TITLE
ensure async

### ISSUE THREAD

**Issue by Kikobeats** [then/nodeify#3]
Hey,

I read the code and I saw you are adding a delay all the time:
https://github.com/then/nodeify/blob/master/index.js#L14

That's is ok, but ideally just it's necessary add the delay for sync code.

Could be possible handle this conditional async delay using something like ensureAsync:
https://caolan.github.io/async/ensureAsync.js.html

**Comment by ForbesLindesay** [comment]
This isn't there to ensure that the code is executed asynchronously.  Promises already do that for free.  It's there to ensure that any exceptions thrown in the callback don't get swallowed by the promise.

**Comment by Kikobeats** [comment]
Oh god, thanks for the clarification!
